Repository musaibasrar/Curium, pull requests merged in 2024-10, with the labels that each got.

#653 Migrated HR processStaffSalary using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/StaffSalaryDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#654 Migrating StudentAction viewDetailsOfStudent uisng adapter.
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesAction.java
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesApiAction.java
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentMapper.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: enhancement, java

#656 Migrated HR getPayHead using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PayHeadDto.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PayHeadResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#662 Migrating StudentAction viewOtherFeesDetailsOfStudent using adapter.
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesAction.java
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesApiAction.java
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: enhancement, java

#664 Migrated HR issueStaffSalary using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/SalaryResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#668 Migrating StudentAction viewAllStudentsList and viewStudentsParentsPerBranch using adapter.
  src/main/java/org/ideoholic/curium/model/appointment/action/AppointmentAction.java
  src/main/java/org/ideoholic/curium/model/appointment/action/AppointmentApiAction.java
  src/main/java/org/ideoholic/curium/model/examdetails/action/ExamDetailsAction.java
  src/main/java/org/ideoholic/curium/model/feescategory/action/FeesActionAdapter.java
  src/main/java/org/ideoholic/curium/model/feescategory/dto/FeescategoryDetailDto.java
  src/main/java/org/ideoholic/curium/model/feescategory/dto/StudentListResponseDto.java
  src/main/java/org/ideoholic/curium/model/feescategory/service/FeesService.java
  src/main/java/org/ideoholic/curium/model/job/action/JobAction.java
  src/main/java/org/ideoholic/curium/model/mess/stockmove/action/MessStockMoveAction.java
  src/main/java/org/ideoholic/curium/model/mess/stockmove/action/MessStockMoveApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: enhancement

#670 Migrated HR printSalarySlip using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/SalarySlipResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#674 Making changes in viewAllStudents and otherviewDetailsOfStudent.
  src/main/java/org/ideoholic/curium/model/mess/item/dto/InvoiceDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: java

#676 Migrated HR getStaffDetails using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/StaffDetailsDto.java
  src/main/java/org/ideoholic/curium/model/hr/dto/StaffDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#680 Migrated HR deletePayHeadStaff using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/StaffDetailsDto.java
  src/main/java/org/ideoholic/curium/model/hr/dto/StaffDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/dto/StaffSalaryDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#682 Creating StudentServiceArchive in student module.
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentServiceArchive.java
Labels: enhancement, java

#688 Updating studentpic delete function in updateStudent method and moving updateStudent to archive.
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentServiceArchive.java
Labels: enhancement, java

#686 Migrated HR cancelProcessedSalary using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#692 Migrated HR updateBasicPayEmployees using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/BasicPayDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#690 Migrating StudentService private method stampFees.
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/CreateStudentDto.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: enhancement, java

#699 Migrated HR viewLeavesDetails using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement
