Repository musaibasrar/Curium, pull requests merged in 2024-09, with the labels that each got.

#595 Creating EmployeeApiActionImpl and EmployeeApiAction.
  src/main/java/org/ideoholic/curium/exceptions/CustomErrorMessage.java
  src/main/java/org/ideoholic/curium/model/employee/action/EmployeeAction.java
  src/main/java/org/ideoholic/curium/model/employee/action/EmployeeActionAdapter.java
  src/main/java/org/ideoholic/curium/model/employee/action/EmployeeApiAction.java
  src/main/java/org/ideoholic/curium/model/employee/action/EmployeeApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/employee/dto/EmployeeDetailsDto.java
  src/main/java/org/ideoholic/curium/model/employee/dto/EmployeeDto.java
  src/main/java/org/ideoholic/curium/model/employee/service/EmployeeService.java
  src/main/java/org/ideoholic/curium/model/user/service/UserService.java
Labels: enhancement, java

#597 Migrating StudentAction viewAllStudentsSuperAdmin, addNew and downlaodFile using adapter.
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentsSuperAdminResponseDto.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: java

#601 Migrated HR viewLeavesDetails using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/LeavesDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#599 Migrating StudentAction generateBonafide, viewfeesStructurePerYear and viewAllStudentsParents using adapter.
  src/main/java/org/ideoholic/curium/model/appointment/action/AppointmentAction.java
  src/main/java/org/ideoholic/curium/model/appointment/action/AppointmentApiAction.java
  src/main/java/org/ideoholic/curium/model/feescollection/dto/FeesDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/mess/item/action/MessItemsAction.java
  src/main/java/org/ideoholic/curium/model/mess/item/action/MessItemsApiAction.java
  src/main/java/org/ideoholic/curium/model/mess/item/action/MessItemsApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/mess/stockmove/action/MessStockMoveAction.java
  src/main/java/org/ideoholic/curium/model/mess/stockmove/action/MessStockMoveApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/parents/dto/ParentListResponseDto.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/BonafideGenerationResponseDto.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentIdDto.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
  src/main/java/org/ideoholic/curium/model/studentdiary/action/StudentDiaryAction.java
Labels: java

#604 Migrating StudentAction promoteMultiple, restoreMultiple, deleteMultiple and viewAllStudentsArchive using adapter.
  src/main/java/org/ideoholic/curium/model/attendance/dto/StudentAttendanceDetailsResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/marksdetails/action/MarksDetailsActionAdapter.java
  src/main/java/org/ideoholic/curium/model/marksdetails/action/MarksDetailsApiAction.java
  src/main/java/org/ideoholic/curium/model/marksdetails/action/MarksDetailsApiActionImpl.java
  src/main/java/org/ideoholic/curium/model/marksdetails/dto/StudentGraphDto.java
  src/main/java/org/ideoholic/curium/model/marksdetails/service/MarksDetailsService.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/PromoteMultipleDto.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentIdsDto.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: java

#607 Migrating StudentAction archiveMultiple, addStudent and exportDataForStudents using adapter.
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
Labels: java

#605 Migrated HR leaveDetailsPerYear using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/LeaveDetailsDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#609 Migrated HR payHead using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PayHeadResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#612 Migrated HR savePayHead using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PayHeadDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#615 Migrated HR addPayHeadStaffDetails using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PayHeadStaffDetailsDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#617 Migrated HR addBasicPay using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/BasicPayDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#624 Migrated HR addPf using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PfSettingsResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#626 Migrated HR deletePf using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/PfDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#629 Migrated HR saveAdvanceSalary using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/SaveAdvanceSalaryDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#631 Migrated HR deleteAdvaceSalaryApproval using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/DeleteAdvaceSalaryApprovalDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#633 Migrated HR salaryApprovalDispaly using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/SalaryApprovalResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#638 Migrated Hr saveAdvanceSalaryApproval using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/AdvanceSalaryApprovalDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#640 Migrated Hr salaryIssue using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/SalaryResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#642 Migrated Hr applyLeave using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/ApplyLeaveDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#644 Migrated Hr leaveApprovals using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/LeaveApprovalsResponseDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#646 Migrated HR rejectLeave using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/LeaveIdsDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#649 Migrated HR approveLeave using Adapter
  src/main/java/org/ideoholic/curium/model/hr/action/HrAction.java
  src/main/java/org/ideoholic/curium/model/hr/action/HrActionAdapter.java
  src/main/java/org/ideoholic/curium/model/hr/dto/LeaveIdsDto.java
  src/main/java/org/ideoholic/curium/model/hr/dto/LeaveTypeDto.java
  src/main/java/org/ideoholic/curium/model/hr/service/HrService.java
Labels: enhancement

#618 Migrating StudentAction updateStudent using adapter.
  src/main/java/org/ideoholic/curium/model/academicyear/dto/Yearmapper.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentAction.java
  src/main/java/org/ideoholic/curium/model/student/action/StudentActionAdapter.java
  src/main/java/org/ideoholic/curium/model/student/dto/CreateStudentDto.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentDto.java
  src/main/java/org/ideoholic/curium/model/student/dto/StudentMapper.java
  src/main/java/org/ideoholic/curium/model/student/service/StudentService.java
  src/main/webapp/WEB-INF/jsp/student_details.jsp
  src/main/webapp/WEB-INF/jsp/student_details_dc.jsp
  src/main/webapp/WEB-INF/jsp/student_update.jsp
  src/main/webapp/WEB-INF/jsp/student_update_dc.jsp
  src/main/webapp/WEB-INF/jsp/student_update_pu.jsp
Labels: java
